import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Logo from './assets/me-6.png'
import NewsSlide from './Components/NewsSlide'
import OtrasNoticias from './OtrasNoticias'

export default function Home({ posts }) {
  console.log(posts)



  return (

    <div className="main-container  center  ">
      <Head>
        <title>Marea Ecologista</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" ">
        <nav className="bg-white w-100">

          <div className="flex flex-wrap justify-around">
            <div className="logo-container mw4 flex flex-wrap justify-around" id="logo">
              <Image id="logo" src={Logo} layout="intrinsic" alt="foto" />
            </div>
            <div>
              <h2 className="black">Something</h2>
            </div>
          </div>
        </nav>

        <NewsSlide/>

        <article className="w8   center bg-white">

          <section className="main bg-silver mw9  center  ba">
            {
              posts.nodes.map(post => {
                const _post = `/posts/${post.slug}`
                return (

                  <div key={post.slug} className="red ba mw8  center  ">
                    <Link href={_post}>
                      <a>
                        <div className="relative">
                          <Image className="" src={post.featuredImage.node.sourceUrl} width={200} height={100} layout="responsive" alt="cover" />
                          <div className="w-100 bg-black pa3 absolute bottom-0 ">
                            <h2 className="titular white f5  ">{post.title}</h2>
                            <p className="white f6" dangerouslySetInnerHTML={{ __html: post.excerpt }}></p>
                            <p className=" f7" dangerouslySetInnerHTML={{ __html: post.date }}></p>
                          </div>

                        </div>
                      </a>
                    </Link>
                  </div >
                )

              })
            }
          </section>
        </article>
      </main>

      <div className="mw8 ba center flex flex-wrap justify-around bg-silver">
        <div className="w-30 ba bg-blue flex  flex-wrap  ">
          <OtrasNoticias />
          <OtrasNoticias />
          <OtrasNoticias />
          <OtrasNoticias />
        </div>
        <div className="mw5 pa2 bg-white ">
          <OtrasNoticias className=" " />
        </div>
      </div>



      <footer>

      </footer>


    </div >


  )
}

export async function getStaticProps() {

  const res = await fetch('https://graciahernandez.com/graphql', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: `
      query AllPostsQuery{
        posts{
          nodes{
            id
            slug
            date
            content
            title
            excerpt
            featuredImage{
              node{
                sourceUrl
              }
            }
          }
        }
      }`
    })
  })
  const json = await res.json();

  return {
    props: {
      posts: json.data.posts,

    },
  }
}